if [ -f ~/.bashrc ] ; then
. ~/.bashrc
fi


#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/lu.tao/.sdkman"
[[ -s "/Users/lu.tao/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/lu.tao/.sdkman/bin/sdkman-init.sh"
export BASH_SILENCE_DEPRECATION_WARNING=1
